aandmysitecopy2/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('chaining/', include('smart_selects.urls')),
    path('', include('home.urls')),
    path('shop/', include('shop.urls')),
    path('news/', include('news.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('faicon/', include('faicon.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('product-specs/', include('specs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', setting),

    path('faq/', faq),
    path('', slider),
    path('privacypolicy/', privacypolicy),
    path('conditionofpayment/', conditionofpayment),
    path('usloviyadostavka/', usloviyadostavka),
    path('garantii/', garantii),
    path('vozvrat/', vozvrat),
    path('contact/', contact),
    path('aboutus/', aboutus),
    path('useragreement/', useragreement),

]

shop/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import (
    BaseView,
    ProductDetailView,
    CategoryDetailView,
    CartView,
    AddToCartView,
    DeleteFromCartView,
    ChangeQTYView,
    CheckoutView,
    MakeOrderView,
    LoginView,
    RegistrationView
)


urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:slug>/', ChangeQTYView.as_view(), name='change_qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page="/"), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),
]

shop/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse
from django.utils import timezone

User = get_user_model()


class Category(models.Model):

    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

class Product(models.Model):

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание', null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')
    features = models.ManyToManyField("specs.ProductFeatures", blank=True, related_name='features_for_product')
    addescription = models.TextField(verbose_name='Дополнительное информация', null=True)
    saleprice = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена по распродаже', null=True)
    pricepoints = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена за баллы')
    rewardpoints = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Вознограждения баллами')
    instock = models.PositiveIntegerField(verbose_name='В наличии', default=1)
    views = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'slug': self.slug})

    def get_features(self):
        return {f.feature.feature_name: ' '.join([f.value, f.feature.unit or ""]) for f in self.features.all()}

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

class CartProduct(models.Model):

    user = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
    product = models.ForeignKey(Product, verbose_name='Товар', on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')

    def __str__(self):
        return "Продукт: {} (для корзины)".format(self.product.title)

    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.product.price
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Тележка Продукта'
        verbose_name_plural = 'Тележка Продукта'

class Cart(models.Model):

    owner = models.ForeignKey('Customer', null=True, verbose_name='Владелец', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name='Общая цена')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'

class Customer(models.Model):

    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адрес', null=True, blank=True)
    orders = models.ManyToManyField('Order', verbose_name='Заказы покупателя', related_name='related_order')

    def __str__(self):
        return "Покупатель: {} {}".format(self.user.first_name, self.user.last_name)


    class Meta:
        verbose_name = 'Покупатель'
        verbose_name_plural = 'Покупатели'

class Order(models.Model):

    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Новый заказ'),
        (STATUS_IN_PROGRESS, 'Заказ в обработке'),
        (STATUS_READY, 'Заказ готов'),
        (STATUS_COMPLETED, 'Заказ выполнен')
    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'Самовывоз'),
        (BUYING_TYPE_DELIVERY, 'Доставка')
    )

    customer = models.ForeignKey(Customer, verbose_name='Покупатель', related_name='related_orders', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=1024, verbose_name='Адрес', null=True, blank=True)
    status = models.CharField(
        max_length=100,
        verbose_name='Статус заказ',
        choices=STATUS_CHOICES,
        default=STATUS_NEW
    )
    buying_type = models.CharField(
        max_length=100,
        verbose_name='Тип заказа',
        choices=BUYING_TYPE_CHOICES,
        default=BUYING_TYPE_SELF
    )
    comment = models.TextField(verbose_name='Комментарий к заказу', null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')
    order_date = models.DateField(verbose_name='Дата получения заказа', default=timezone.now)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class Setting(models.Model):

    skinshop = models.ImageField(blank=True, upload_to='image', null=True, verbose_name='Обложка магазина')
    skinshopcat = models.ImageField(blank=True, upload_to='image', null=True, verbose_name='Обложка категории')
    skinshopprod = models.ImageField(blank=True, upload_to='image', null=True, verbose_name='Обложка товара')
    sber = models.BooleanField(default=False, verbose_name='Использовать платежную сестему Сбербанка')
    sberlogin = models.CharField(max_length=255, db_index=True, blank=True, verbose_name='Логин')
    sberpass = models.CharField(max_length=255, db_index=True, blank=True, verbose_name='Пароль')
    yand = models.BooleanField(default=False, verbose_name='Использовать платежную сестему Яндекса')
    yanlogin = models.CharField(max_length=255, db_index=True, blank=True, verbose_name='Логин')
    yanpass = models.CharField(max_length=255, db_index=True, blank=True, verbose_name='Пароль')
    alfa = models.BooleanField(default=False, verbose_name='Использовать платежную сестему Альфа Банка')
    allogin = models.CharField(max_length=255, db_index=True, blank=True, verbose_name='Логин')
    alpass = models.CharField(max_length=255, db_index=True, blank=True, verbose_name='Пароль')
    cdek = models.BooleanField(default=False, verbose_name='Использовать службу доставки СДЭК')
    cdeklogin = models.CharField(max_length=255, db_index=True, blank=True, verbose_name='Логин')
    cdekpass = models.CharField(max_length=255, db_index=True, blank=True, verbose_name='Пароль')
    pochros = models.BooleanField(default=False, verbose_name='Использовать службу доставки Почта России')
    prlogin = models.CharField(max_length=255, db_index=True, blank=True, verbose_name='Логин')
    prpass = models.CharField(max_length=255, db_index=True, blank=True, verbose_name='Пароль')

    class Meta:
        verbose_name = "Настройка"
        verbose_name_plural = "Настройки"

shop/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Order

User = get_user_model()


class OrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['order_date'].label = 'Дата получения заказа'

    order_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Order
        fields = (
            'first_name', 'last_name', 'phone', 'address', 'buying_type', 'order_date', 'comment'
        )


class LoginForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Пользователь с логином "{username} не найден в системе')
        user = User.objects.filter(username=username).first()
        if user:
            if not user.check_password(password):
                raise forms.ValidationError("Неверный пароль")
        return self.cleaned_data


class RegistrationForm(forms.ModelForm):

    confirm_password = forms.CharField(widget=forms.PasswordInput)
    password = forms.CharField(widget=forms.PasswordInput)
    phone = forms.CharField(required=False)
    address = forms.CharField(required=False)
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'
        self.fields['confirm_password'].label = 'Подтвердите пароль'
        self.fields['phone'].label = 'Номер телефона'
        self.fields['first_name'].label = 'Имя'
        self.fields['last_name'].label = 'Фамилия'
        self.fields['address'].label = 'Адрес'
        self.fields['email'].label = 'Электронная почта'

    def clean_email(self):
        email = self.cleaned_data['email']
        domain = email.split('.')[-1]
        if domain in ['com', 'net']:
            raise forms.ValidationError(
                f'Регистрация для домена {domain} невозможна'
            )
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                f'Данный почтовый адрес уже зарегистрирован в системе'
            )
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(
                f'Имя {username} занято'
            )
        return username

    def clean(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('Пароли не совпадают')
        return self.cleaned_data

    class Meta:
        model = User
        fields = ['username', 'password', 'confirm_password', 'first_name', 'last_name', 'address', 'phone', 'email']

templates/shop/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
(function($) {
    $('#id_sd').on('click', function(){
        if($('#id_sd').prop('checked') == true){
            $('#id_sd_volume_max').prop('readonly', false)
            $('#id_sd_volume_max').val('')
            $('#id_sd_volume_max').css('background', 'white')
        }else{
            $('#id_sd_volume_max').prop('readonly', true)
            $('#id_sd_volume_max').val('')
            $('#id_sd_volume_max').css('background', 'lightgray')
        }
    })
})(django.jQuery);
</script>
{% endblock %}

templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Shop Homepage - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <!-- Custom styles for this template -->
  <link href="css/shop-homepage.css" rel="stylesheet">

</head>
<style>
    body {
      padding-top: 56px;
    }
</style>
<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'base' %}">Django 3 | E-commerce</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav">
            {% if not request.user.is_authenticated %}
          <li>
            <a class="nav-link text-white" href="{% url 'login' %}">Авторизация</a>
          </li>
            <li>
            <a class="nav-link text-white" href="{% url 'registration' %}">Регистрация</a>
          </li>
          {% else %}
              <li class="nav-item">
                  <span class="navbar-text text-light">Здравствуйте, {% if request.user.is_authenticated %}<span class="badge badge-danger"><a href="#" style="text-decoration: none; font-size: 14px;">{{ request.user.username }}</a></span>{% else %} гоcть!{% endif %}<a href="{% url 'logout' %}">| Выйти</a></span>
              </li>
          {% endif %}


            <li class="user_icon" >
                                  <button type="button" class="user_icon " style="border: 0px; background: #fff;"data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <a href="#"><i class="icon-user icons"></i></a>
                                  </button>
                                  <div class=" dropdown-menu dropdown-menu-right">

                                      <button class="dropdown-item" type="button" href="{% url 'login' %}">Авторизация</button>

                                  </div>
                                </li>


          </ul>
          <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart' %}">Корзина <span class="badge badge-pill badge-danger">{{ cart.products.count }}</span></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3 mt-5">
        <div class="list-group">
          {% for category in categories %}
          <a href="{{ category.get_absolute_url }}" class="list-group-item">{{ category.name }} ({{ category.product_set.count }})</a>
          {% endfor %}
        </div>
      {% block productfilter %}
      {% endblock productfilter %}
      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">
        {% block content %}
        {% if messages %}
            {% for message in messages %}
              <div class="alert alert-success alert-dismissible fade show mt-3" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %}
        {% endif %}

        <div class="row mt-5">
          {% for product in products %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </h4>
                <h5>{{ product.price }} руб.</h5>
                <a href="{% url 'add_to_cart' slug=product.slug %}">
                  <button class="btn btn-danger">Добавить в корзину</button>
                </a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <!-- /.row -->
      {% endblock content %}
      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

templates/shop/cart.html
{% extends 'shop/base.html' %}

{% block content %}
<h3 class="text-center mt-5 mb-5">Ваша корзина {% if not cart.products.count %}пуста{% endif %}</h3>
{% if messages %}
    {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
{% endif %}
{% if cart.products.count %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Наименование</th>
      <th scope="col">Изображение</th>
      <th scope="col">Цена</th>
      <th scope="col">Кол-во</th>
        <th scope="col">Общая цена</th>
      <th scope="col">Действие</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart.products.all %}
        <tr>
          <th scope="row">{{ item.product.title }}</th>
          <td class="w-25"><img src="{{ item.product.image.url }}" class="img-fluid"></td>
          <td>{{ item.content_object.price }} руб.</td>
          <td>
            <form action="{% url 'change_qty' slug=item.product.slug %}" method="POST">
              {% csrf_token %}
              <input type="number" class="form-control" name="qty" style="width: 70px;" min="1" value="{{ item.qty }}">
              <br>
              <input type="submit" class="btn btn-primary" value="Изменить кол-во">
            </form>
          </td>
            <td>{{ item.final_price }} руб.</td>
          <td>
            <a href="{% url 'delete_from_cart' slug=item.product.slug %}"><button class="btn btn-danger">Удалить из корзины</button></a>
          </td>
        </tr>
    {% endfor %}
        <tr>
          <td colspan="2"></td>
          <td>Итого:</td>
          <td>{{ cart.total_products }}</td>
          <td><strong>{{ cart.final_price }} руб.</strong></td>
          <td><a href="{% url 'checkout' %}"><button class="btn btn-primary">Перейти к оформлению</button></a></td>
        </tr>
  </tbody>
</table>
{% endif %}
{% endblock content %}

templates/shop/category_detail.html
{% extends 'shop/base.html' %}
{% load search_filter %}

{% block productfilter %}

      <form class="d-flex mt-3" action="{% url 'category_detail' slug=category.slug %}" method="GET">
        <input class="form-control me-2" name="search" type="search" placeholder="Поиск товара" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Поиск</button>
      </form>
    <hr>
    <form action="{% url 'category_detail' slug=category.slug %}" method="GET">
        {{ category|product_spec }}
    <p class="text-center">
        <button class="btn btn-outline-success" type="submit">Поиск</button>
        <button class="btn btn-outline-info" type="submit">Сбросить</button>
    </p>
    </form>

{% endblock productfilter %}
{% block content %}
    <nav aria-label="breadcrumb" class="mt-5">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
        <li class="breadcrumb-item active">{{ category.name }}</li>
      </ol>
    </nav>
<div class="row">
  {% for product in category_products %}
  <div class="col-lg-4 col-md-6 mb-4">
    <div class="card h-100">
      <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt=""></a>
      <div class="card-body">
        <h4 class="card-title">
          <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
        </h4>
        <h5>{{ product.price }} руб.</h5>
              <a href="{% url 'add_to_cart' slug=product.slug %}">
      <button class="btn btn-danger">Добавить в корзину</button>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock content %}

templates/shop/checkout.html
{% extends 'shop/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h3 class="text-center mt-5 mb-5">Оформление заказа</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Наименование</th>
      <th scope="col">Изображение</th>
      <th scope="col">Цена</th>
      <th scope="col">Кол-во</th>
        <th scope="col">Общая цена</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart.products.all %}
        <tr>
          <th scope="row">{{ item.product.title }}</th>
          <td class="w-25"><img src="{{ item.product.image.url }}" class="img-fluid"></td>
          <td>{{ item.product.price }} руб.</td>
          <td>{{ item.qty }}</td>
            <td>{{ item.final_price }} руб.</td>
        </tr>
    {% endfor %}
        <tr>
          <td colspan="2"></td>
          <td>Итого:</td>
          <td>{{ cart.total_products }}</td>
          <td><strong>{{ cart.final_price }} руб.</strong></td>
        </tr>
  </tbody>
</table>
<hr>
<h3 class="text-center mt-5 mb-5">Форма заказа</h3>
<form action="{% url 'make_order' %}" method="POST">
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" class="btn btn-success btn-block mb-3" values="Оформить заказ">
</form>
{% endblock content %}

templates/shop/login.html
{% extends 'shop/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row" style="margin-bottom: 200px; margin-top: 160px">
<div class="col-md-6 offset-md-3">
    <h3 class="text-center">Авторизация</h3>
    <hr>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-success btn-block" value="Войти">
    </form>
</div>

</div>
{% endblock %}

templates/shop/product_detail.html
{% extends 'shop/base.html' %}

{% block content %}
    <nav aria-label="breadcrumb" class="mt-5">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
        <li class="breadcrumb-item"><a href="{{ product.category.get_absolute_url }}">{{ product.category.name }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ product.title }}</li>
      </ol>
    </nav>
<div class="row">
    <div class="col-md-4">
        <img src="{{ product.image.url }}" class="img-fluid">
    </div>
    <div class="col-md-8">
        <h3>{{ product.title }}</h3>
        <p>Цена: {{ product.price }} руб.</p>
        <p>Описание: {{ product.description }}</p>
        <hr>
        <a href="{% url 'add_to_cart' slug=product.slug %}"><button class="btn btn-danger">Добавить в корзину</button></a>
    </div>
    <p class="mt-4">Характеристики:</p>
    <table class="table">
      <tbody>
      {% for f_name, f_value in product.get_features.items %}
        <tr>
          <th scope="row">{{ f_name }}</th>
          <td>{{ f_value }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
</div>

{% endblock content %}

templates/shop/registration.html
{% extends 'shop/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row" style="margin-bottom: 50px; margin-top: 50px">
<div class="col-md-6 offset-md-3">
    <h3 class="text-center">Регистрация нового пользователя</h3>
    <hr>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-success btn-block" value="Зарегистрироваться">
    </form>
</div>

</div>
{% endblock %}